[colors.primary]
background = "#282a36"
foreground = "#f8f8f2"
dim_foreground = "#6272a4"
bright_foreground = "#ffffff"

[colors.cursor]
text = "#282a36"
cursor = "#f8f8f2"

[colors.vi_mode_cursor]
text = "#282a36"
cursor = "#50fa7b"

[colors.search.matches]
foreground = "#282a36"
background = "#ffb86c"

[colors.search.focused_match]
foreground = "#282a36"
background = "#8be9fd"

[colors.footer_bar]
foreground = "#282a36"
background = "#6272a4"

[colors.hints.start]
foreground = "#282a36"
background = "#ff79c6"

[colors.hints.end]
foreground = "#282a36"
background = "#6272a4"

[colors.selection]
text = "#282a36"
background = "#44475a"

[colors.normal]
black = "#21222c"
red = "#ff5555"
green = "#50fa7b"
yellow = "#f1fa8c"
blue = "#bd93f9"
magenta = "#ff79c6"
cyan = "#8be9fd"
white = "#f8f8f2"

[colors.bright]
black = "#6272a4"
red = "#ff6e6e"
green = "#69ff94"
yellow = "#ffffa5"
blue = "#d6acff"
magenta = "#ff92df"
cyan = "#a4ffff"
white = "#ffffff"

[colors.dim]
black = "#21222c"
red = "#ff5555"
green = "#50fa7b"
yellow = "#f1fa8c"
blue = "#bd93f9"
magenta = "#ff79c6"
cyan = "#8be9fd"
white = "#f8f8f2"

[[colors.indexed_colors]]
index = 16
color = "#ffb86c"

[[colors.indexed_colors]]
index = 17
color = "#bd93f9"
